### ISSUE TITLE
Bug in Finder sidebar when Time Machine is backing up

### ISSUE THREAD

**Issue by VisualisationExpo** [i-pwl/airbrush#9]
There's an animation issue going on with the Finder sidebar and the airbrush plugin.

https://user-images.githubusercontent.com/86615159/191406798-3b8e58b4-3668-48f5-9485-f45c367d9079.mov

It resettles when the mouse cursor hovers over the backing up symbol in the Finder sidebar, but returns on the next backup

OS: macOS 12.6
Architecture: Intel Mac
Airbrush: release v5
MacForge: latest official build from website - same issue occurs on MacForge `fix-beta` branch builds

**Solution: drag the Time Machine HD icon out from the Sidebar**

**Comment by i-pwl** [comment]
gave this the "wontfix" until airbrush v2 (AKA Glow) is released
